[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.session"]

[phases.install]
cmds = ["mkdir -p uploads/info uploads/qris uploads/receipts uploads/settlements"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} router.php"
